checks:
  # Enable additional security checks
  addAllBuiltIn: true
  exclude:
    # Resource limits not yet required
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    # Not needed for single-node lab
    - "minimum-three-replicas"
    # Metadata verbose for solo project
    - "required-annotation-email"
    - "required-label-owner"
    # HA features not required
    - "no-node-affinity"
    - "no-rolling-update-strategy"
    # Not relevant for standard apps
    - "dnsconfig-options"
    # Standard for web services
    - "privileged-ports"
    # Handled globally
    - "non-isolated-pod"
    # Base applications convenience
    - "default-service-account"
    # Standard images need write access
    - "no-read-only-root-fs"
    # Deployments default to 'Always'
    - "restart-policy"
